services:
  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    command: [ "proxy" ]
    ports:
      - "2000:2000"

  native:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: [ "2001", "native" ]

  xml:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: [ "2002", "xml" ]

  json:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: [ "2003", "json" ]

  proto:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: [ "2004", "proto" ]

  avro:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: [ "2005", "avro" ]

  yaml:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: [ "2006", "yaml" ]

  mpack:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: [ "2007", "mpack" ]
