services:
  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    command: [ "proxy" ]
    ports:
      - "2000:2000"

  native:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: [ "1111", "native" ]


  xml:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: [ "2222", "xml" ]
